config = {'data_filename': 'output.out',
          'starting_point': {'x': 0.0, 'y': 0.0},
          'starting_tangent_angle': 0.0,
          'arc_sample_count': 10,
          'sample_count': 500,
          'allow_intersections': False,
          'min_line_distance': 0.05,
          'max_line_distance': 0.15,
          'min_radius': 0.1,
          'max_radius': 0.3,
          'max_angle_factor': 1.0,
          'attempt_max': 10,
          'random_seed': 405,
          'curve_choices': ('arc', 'arc', 'line'),
          'arc_direction_choices': (False, True)}
